#Info taken from [https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-Configuration-File.md]
behaviors:
  GGBond:
    trainer_type: sac

    # Trainer configs common to PPO/SAC (excluding reward signals)
    # same as PPO config

    # SAC-specific configs (replaces the hyperparameters section above)
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 1024
      buffer_size: 100000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant

      # SAC-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 1
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 1

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
    
    # Trainer configurations common to all trainers
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true # allows environment to run while updates happen. Might speed up progress but should be turned off for best performance when using self-play
    init_path: null

    reward_signals:
      # environment reward
      extrinsic:
        strength: 1.0
        gamma: 0.99